name: Build
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14.4' # The Go version to download (if necessary) and use.

      - name: Get dependencies
        run: |
          go version
          go get -v -t ./...

      - name: Unit Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic -short ./...

      - name: Build
        run: |
          go build -v .

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
  
  functional_test:
    name: Functional Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go version
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14.4' # The Go version to download (if necessary) and use.
    
      - name: Run tests
        run: make test_functional
      
      - name: E2E test for build binary
        run: make test_e2e_cmd
